name: Build Multi-arch Image

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: quay.io

      - name: Build and Push Image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfiles/ocp4_content
          tags: quay.io/vahirwad/ocp4:latest
          platforms: linux/amd64,linux/ppc64le
          push: true
