---
name: Kubernetes content

on:
  push:
    branches: [ 'master' ]

jobs:
  container-main:
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: varad-ahirwadkar/container-push/.github/workflows/container-push.yml@main
    with:
      name: k8scontent
      tag: latest
      registry_org: varad-ahirwadkar
      dockerfile_path: ./Dockerfiles/ocp4_content
      licenses: BSD
      vendor: ComplianceAsCode authors
      platform: linux/amd64,linux/ppc64le
